const colors = [
   { bgColor: "bg-black", textcolor: "text-black" },
   { bgColor: "bg-white", textcolor: "text-white" },
   { bgColor: "bg-slate-100", textcolor: "text-slate-100" },
   { bgColor: "bg-slate-200", textcolor: "text-slate-200" },
   { bgColor: "bg-slate-300", textcolor: "text-slate-300" },
   { bgColor: "bg-slate-400", textcolor: "text-slate-400" },
   { bgColor: "bg-slate-500", textcolor: "text-slate-500" },
   { bgColor: "bg-slate-600", textcolor: "text-slate-600" },
   { bgColor: "bg-slate-700", textcolor: "text-slate-700" },
   { bgColor: "bg-slate-800", textcolor: "text-slate-800" },
   { bgColor: "bg-slate-900", textcolor: "text-slate-900" },
   { bgColor: "bg-rose-100", textcolor: "text-rose-100" },
   { bgColor: "bg-rose-200", textcolor: "text-rose-200" },
   { bgColor: "bg-rose-300", textcolor: "text-rose-300" },
   { bgColor: "bg-rose-400", textcolor: "text-rose-400" },
   { bgColor: "bg-rose-500", textcolor: "text-rose-500" },
   { bgColor: "bg-rose-600", textcolor: "text-rose-600" },
   { bgColor: "bg-rose-700", textcolor: "text-rose-700" },
   { bgColor: "bg-rose-800", textcolor: "text-rose-800" },
   { bgColor: "bg-rose-900", textcolor: "text-rose-900" },
   { bgColor: "bg-gray-100", textcolor: "text-gray-100" },
   { bgColor: "bg-gray-200", textcolor: "text-gray-200" },
   { bgColor: "bg-gray-300", textcolor: "text-gray-300" },
   { bgColor: "bg-gray-400", textcolor: "text-gray-400" },
   { bgColor: "bg-gray-500", textcolor: "text-gray-500" },
   { bgColor: "bg-gray-600", textcolor: "text-gray-600" },
   { bgColor: "bg-gray-700", textcolor: "text-gray-700" },
   { bgColor: "bg-gray-800", textcolor: "text-gray-800" },
   { bgColor: "bg-gray-900", textcolor: "text-gray-900" },
   { bgColor: "bg-stone-100", textcolor: "text-stone-100" },
   { bgColor: "bg-stone-200", textcolor: "text-stone-200" },
   { bgColor: "bg-stone-300", textcolor: "text-stone-300" },
   { bgColor: "bg-stone-400", textcolor: "text-stone-400" },
   { bgColor: "bg-stone-500", textcolor: "text-stone-500" },
   { bgColor: "bg-stone-600", textcolor: "text-stone-600" },
   { bgColor: "bg-stone-700", textcolor: "text-stone-700" },
   { bgColor: "bg-stone-800", textcolor: "text-stone-800" },
   { bgColor: "bg-stone-900", textcolor: "text-stone-900" },
];

export default colors;